from dataclasses import dataclass
from typing import Any, Callable, Literal, Never, Sequence, cast

import fol
from folio_oneshot import (
    Z3_TIMEOUT,
    APIType,
    FormalizeIP,
    OneShotIP,
    ReflectFlag,
    ReflectFlagTag,
    StyleFlag,
    StyleFlagTag,
    Verdict,
    check_constraints,
    dummy_fallback_policy,
    folio_oneshot,
    folio_oneshot_policy,
    reflect_policy,
)

import delphyne as dp
from delphyne import Branch, Fail, Run, Strategy, strategy


@dataclass
class Aggregation(dp.Node):
    """
    Node type for the singleton trees induced by `aggregate`.
    """

    space: dp.OpaqueSpace[Any, Any]
    aggreg: Callable[[Sequence[Any]], dp.OpaqueSpace[Any, Any]] | None = None

    def navigate(self) -> dp.Navigation:
        return (yield self.space)


@strategy(name="aggregate")
def _aggregate[P, T](
    space: dp.Opaque[P, T],
    aggreg: Callable[[Sequence[T]], dp.Opaque[P, Sequence[T]]] | None = None,
) -> dp.Strategy[Aggregation, P, Sequence[T]]:
    recv = yield dp.spawn_node(Aggregation, space=space, aggreg=aggreg)
    sols = cast(Sequence[T], recv.action)
    return sols


@dp.search_policy
def _search_aggregation[P, U](
    tree: dp.Tree[Aggregation, P, U],
    env: dp.PolicyEnv,
    policy: P,
) -> dp.StreamGen[U]:
    assert isinstance(tree.node, Aggregation)
    sols = yield from tree.node.space.stream(env, policy).all()

    trackeds = [sol.tracked for sol in sols]
    child = tree.child(trackeds)
    if tree.node.aggreg is not None:
        aggregated = (
            yield from tree.node.aggreg(
                [tracked.value for tracked in trackeds]
            )
            .stream(env, policy)
            .first()
        )
        if aggregated is not None:
            child = tree.child(aggregated.tracked)

    assert isinstance(child.node, dp.Success)
    yield dp.Solution(child.node.success)


def aggregate[P, T](
    space: dp.Opaque[P, T],
    aggreg: Callable[[Sequence[T]], dp.Opaque[P, Sequence[T]]] | None = None,
    inner_policy_type: type[P] | None = None,
) -> Strategy[Run, P, Sequence[T]]:
    """Aggregate all values generated by an opaque space into a sequence."""

    def aggregate_policy(inner_policy: P):
        return _search_aggregation() & inner_policy

    values = yield from dp.run(_aggregate(space).using(aggregate_policy))
    if aggreg is not None:
        aggregated = yield from dp.run(aggreg(values))
    else:
        aggregated = values
    return aggregated


@dataclass
class FolioAggregateIP:
    oneshot: dp.Policy[
        Branch | Fail | dp.Flag[ReflectFlag] | dp.Flag[StyleFlag],
        OneShotIP,
    ]
    evaluate: dp.Policy[Branch | Fail, FormalizeIP]


type AggregationFlagTag = Literal["majority_vote", "favor_unsat", "evaluate"]
type SequenceType = Literal["mixed", "all_normal", "all_normal_reflect"]


@dataclass
class AggregationType(dp.FlagQuery[AggregationFlagTag]):
    """Aggregation type flag."""


@dataclass
class JudgeResults(dp.Query[dp.Response[fol.StrFormalization, Never]]):
    context: list[str]
    results: Sequence[Verdict]
    prefix: dp.AnswerPrefix

    __parser__ = dp.structured.response


@strategy
def evaluate_results(
    puzzle: str,
    results: Sequence[Verdict],
) -> Strategy[Branch | Fail, FormalizeIP, Sequence[Verdict]]:
    yield from dp.ensure(len(results) > 0)
    response = yield from dp.interact(
        step=lambda prefix, _: JudgeResults(
            context=puzzle.strip().split("\n"), results=results, prefix=prefix
        ).using(lambda p: p.formalize, FormalizeIP),
        process=lambda refined_formalization, _: check_constraints(
            refined_formalization, step_type="All"
        ).using(lambda p: p.check, FormalizeIP),
    )
    sol = (
        True
        if response.status == "unsat"
        else False
        if response.status == "sat"
        else None
    )
    return [
        Verdict(None, None, response.formalizations, None, sol, sol),
        *results,
    ]


@strategy
def folio_aggregate(
    puzzle: str,
) -> Strategy[
    Run | Fail | dp.Flag[AggregationType],
    FolioAggregateIP,
    tuple[bool | None, Sequence[Verdict]],
]:
    aggregation_type = yield from dp.get_flag(AggregationType)
    solutions = yield from aggregate(
        space=folio_oneshot(puzzle=puzzle).using(
            lambda p: p.oneshot, FolioAggregateIP
        ),
        inner_policy_type=FolioAggregateIP,
        aggreg=(
            lambda results: evaluate_results(puzzle, results).using(
                lambda p: p.evaluate, FolioAggregateIP
            )
        )
        if aggregation_type == "evaluate"
        else None,
    )
    results = [
        sol.final_solution
        for sol in solutions
        if sol.final_solution is not None
    ]
    yield from dp.ensure(len(results) > 0)

    if aggregation_type == "evaluate":
        res = solutions[0].final_solution
    elif aggregation_type == "favor_unsat":
        res = any(results)
    else:
        assert aggregation_type == "majority_vote"
        res = sum(1 for r in results if r) >= len(results) / 2

    return res, solutions


@dp.ensure_compatible(folio_aggregate)
def folio_aggregate_policy(
    model_name: dp.StandardModelName = "gpt-5-nano",
    reasoning_effort: dp.ReasoningEffort = "low",
    max_rounds_each: int = 5,
    sequence_type: SequenceType = "mixed",
    number_of_experts: int = 3,
    aggregation_type: AggregationFlagTag = "evaluate",
    api_type: APIType = "chat_completions",
) -> dp.Policy[Run | Fail | dp.Flag[AggregationType], FolioAggregateIP]:
    def make_oneshot_policy(
        style_flag: StyleFlagTag, reflect_flag: ReflectFlagTag
    ):
        return folio_oneshot_policy(
            model_name=model_name,
            reasoning_effort=reasoning_effort,
            max_rounds=max_rounds_each,
            style_flag=style_flag,
            reflect_flag=reflect_flag,
            api_type=api_type,
        )

    oneshot_policy_literally = make_oneshot_policy(
        style_flag="literally", reflect_flag="always"
    )
    oneshot_policy_normal = make_oneshot_policy(
        style_flag="normal", reflect_flag="always"
    )
    oneshot_policy_implicitly = make_oneshot_policy(
        style_flag="implicitly", reflect_flag="always"
    )
    oneshot_policy_normal_reflect = make_oneshot_policy(
        style_flag="normal", reflect_flag="always"
    )

    sequence = (
        (
            oneshot_policy_literally,
            oneshot_policy_normal,
            oneshot_policy_implicitly,
        )
        if sequence_type == "mixed"
        else (oneshot_policy_normal_reflect,) * number_of_experts
        if sequence_type == "all_normal_reflect"
        else (oneshot_policy_normal,) * number_of_experts
    )

    oneshot = dp.take(number_of_experts) @ dp.sequence(sequence)
    evaluate = reflect_policy(
        model_name=model_name,
        reasoning_effort=reasoning_effort,
        temperature=0.0,
        timeout_in_seconds=Z3_TIMEOUT,
        max_depth=max_rounds_each,
        api_type=api_type,
    ).or_else(dummy_fallback_policy())

    return dp.dfs() @ dp.elim_flag(
        AggregationType, aggregation_type
    ) & FolioAggregateIP(
        oneshot=oneshot,
        evaluate=evaluate,
    )
