from dataclasses import dataclass
from typing import Any, Callable, Literal, Sequence, cast

import folio_baseline as fb

import delphyne as dp
from delphyne import Branch, Fail, Run, Strategy, strategy

# from delphyne.stdlib.streams import majority_vote


@dataclass
class Aggregation(dp.Node):
    """
    Node type for the singleton trees induced by `aggregate`.
    """

    space: dp.OpaqueSpace[Any, Any]
    aggreg: Callable[[Sequence[Any]], dp.OpaqueSpace[Any, Any]] | None = None

    def navigate(self) -> dp.Navigation:
        return (yield self.space)


@strategy(name="aggregate")
def _aggregate[P, T](
    space: dp.Opaque[P, T],
    aggreg: Callable[[Sequence[T]], dp.Opaque[P, Sequence[T]]] | None = None,
) -> dp.Strategy[Aggregation, P, Sequence[T]]:
    recv = yield dp.spawn_node(Aggregation, space=space, aggreg=aggreg)
    sols = cast(Sequence[T], recv.action)
    return sols


@dp.search_policy
def _search_aggregation[P, U](
    tree: dp.Tree[Aggregation, P, U],
    env: dp.PolicyEnv,
    policy: P,
) -> dp.StreamGen[U]:
    assert isinstance(tree.node, Aggregation)
    sols = yield from tree.node.space.stream(env, policy).all()

    trackeds = [sol.tracked for sol in sols]
    child = tree.child(trackeds)
    if tree.node.aggreg is not None:
        aggregated = (
            yield from tree.node.aggreg(
                [tracked.value for tracked in trackeds]
            )
            .stream(env, policy)
            .first()
        )
        if aggregated is not None:
            child = tree.child(aggregated.tracked)

    assert isinstance(child.node, dp.Success)
    yield dp.Solution(child.node.success)


def aggregate[P, T](
    space: dp.Opaque[P, T],
    aggreg: Callable[[Sequence[T]], dp.Opaque[P, Sequence[T]]] | None = None,
    inner_policy_type: type[P] | None = None,
) -> Strategy[Run, P, Sequence[T]]:
    """Aggregate all values generated by an opaque space into a sequence."""

    def aggregate_policy(inner_policy: P):
        return _search_aggregation() & inner_policy

    values = yield from dp.run(_aggregate(space).using(aggregate_policy))
    if aggreg is not None:
        aggregated = yield from dp.run(aggreg(values))
    else:
        aggregated = values
    return aggregated


@dataclass
class FolioAggregateIP:
    oneshot: dp.Policy[
        Branch | Fail | dp.Flag[fb.ReflectFlag] | dp.Flag[fb.StyleFlag],
        fb.OneShotIP,
    ]


type AggregationFlagTag = Literal["majority_vote", "favor_unsat"]
type SequenceType = Literal["mixed", "all_normal", "all_normal_reflect"]


@dataclass
class AggregationType(dp.FlagQuery[AggregationFlagTag]):
    """Aggregation type flag."""


@strategy
def folio_aggregate(
    puzzle: str,
) -> Strategy[
    Run | Fail | dp.Flag[AggregationType],
    FolioAggregateIP,
    tuple[bool | None, Sequence[fb.Verdict]],
]:
    solutions = yield from aggregate(
        space=fb.folio_oneshot(puzzle=puzzle).using(
            lambda p: p.oneshot, FolioAggregateIP
        ),
        inner_policy_type=FolioAggregateIP,
    )
    results = [
        sol.final_solution
        for sol in solutions
        if sol.final_solution is not None
    ]
    yield from dp.ensure(len(results) > 0)
    aggregation_type = yield from dp.get_flag(AggregationType)
    if aggregation_type == "favor_unsat":
        res = any(results)
    else:
        assert aggregation_type == "majority_vote"
        res = sum(1 for r in results if r) >= len(results) / 2

    return res, solutions


@dp.ensure_compatible(folio_aggregate)
def folio_aggregate_policy(
    model_name: dp.StandardModelName = "gpt-5-nano",
    reasoning_effort: dp.ReasoningEffort = "low",
    max_rounds_each: int = 5,
    sequence_type: SequenceType = "mixed",
    aggregation_type: AggregationFlagTag = "majority_vote",
    api_type: fb.APIType = "chat_completions",
) -> dp.Policy[Run | Fail | dp.Flag[AggregationType], FolioAggregateIP]:
    def make_oneshot_policy(
        style_flag: fb.StyleFlagTag, reflect_flag: fb.ReflectFlagTag
    ):
        return fb.folio_oneshot_policy(
            model_name=model_name,
            reasoning_effort=reasoning_effort,
            max_rounds=max_rounds_each,
            style_flag=style_flag,
            reflect_flag=reflect_flag,
            api_type=api_type,
        )

    oneshot_policy_literally = make_oneshot_policy(
        style_flag="literally", reflect_flag="only_if_sat"
    )
    oneshot_policy_normal = make_oneshot_policy(
        style_flag="normal", reflect_flag="never"
    )
    oneshot_policy_implicitly = make_oneshot_policy(
        style_flag="implicitly", reflect_flag="only_if_unsat"
    )
    oneshot_policy_normal_reflect = make_oneshot_policy(
        style_flag="normal", reflect_flag="always"
    )

    sequence = (
        (
            oneshot_policy_literally,
            oneshot_policy_normal,
            oneshot_policy_implicitly,
        )
        if sequence_type == "mixed"
        else (oneshot_policy_normal_reflect,) * 3
        if sequence_type == "all_normal_reflect"
        else (oneshot_policy_normal,) * 3
    )

    oneshot = (
        # majority_vote(are_equivalent=lambda x, y: x[1] == y[1])  # type: ignore
        dp.take(3) @ dp.sequence(sequence)
    )
    return dp.dfs() @ dp.elim_flag(
        AggregationType, aggregation_type
    ) & FolioAggregateIP(oneshot=oneshot)
